M48
; DRILL file {KiCad 6.0.1+dfsg-1~bpo11+1} date Fri 11 Feb 2022 08:42:25 AM CST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-11T08:42:25-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X40.132Y-42.672
X40.64Y-146.812
X237.744Y-72.136
X238.76Y-146.558
T0
M30
